### ISSUE TITLE
Margin & Periods?

### ISSUE THREAD

**Issue by xiaoyongzhu** [perslev/U-Time#1]
Hi,

This is really a great repo! Looking thru the code & configs, I'm confused by two concept - margin and period (since I met an exception `Margin too large for dataset length`).

Can you explain a bit more on those two concepts?

**Comment by perslev** [comment]
Hi,

Thank you for your interest! I realise there are quite a few concepts that require explanation. I intend to add a detailed description of the repo to the README as soon as I find time (within the next few weeks I expect).

Regarding the 'margin' and 'period' concepts:
- A 'period' is - in lack of a better description - some fixed length segment of the input signal. Across the code this term is used rather interchangeably with 'epoch' (a term adapted from sleep medicine - not to be confused with its ML counterpart) or 'segment'. It could for instance be 3000 connected samples from the input sequence (e.g. 30 seconds of 100 Hz signal). In our application of sleep staging, a 'period' almost always amounts to 30 seconds of input signal, because this is the resolution at which we normally have human annotations (annotators provide us 1 sleep stage score for every 30 seconds of signal). However, with U-Time, in inference a period could be shorter - say 10 seconds - if we want to output a higher resolution segmentation.
- The 'margin' parameter is the number of such 'periods' that the model receives as input bordering a center 'period'. That is, the total number of periods that the model takes as input is 2*'margin' + 1, e.g. 35 for margin=17 (T=35 using the notation of the paper). I realise that this is a little confusing!

Most likely you experienced this exception because your input data sequence is shorter than (2 * margin + 1) * 'data_per_period', where 'data_per_period' would be the sample rate times the length in seconds of 1 'period', which defaults to 30 seconds.

To be honest, explaining this I realise that the notation is a bit confusion. The U-Time implementation is probably implicitly 'biased' towards the realm of sleep staging, as U-Time was at least initially a research project designed for this setting specifically. If you experience further problems applying this implementation to some other domain (or the same...!), I would be happy to discuss and implement changes needed to make the code more generally applicable.

I hope this casts some light.

Cheers,
Mathias

**Comment by xiaoyongzhu** [comment]
Thanks - this is really helpful! I find it useful in other scenario as well, but definitely need to understand the code in order to apply it to other domains.

**Comment by xiaoyongzhu** [comment]
So a follow up question - say if I have a smaller sample rate (say 2 Hz), and I also want to reduce the "period" since we need finer granularity (maybe using 5 to 10 samples), in order to make the CNN part work, I guess I need to reduce the period parameter (to make it finer granularity) and increase the margin?

**Comment by Kuanting1224** [comment]
How do I download dataset?
I use "ut fetch --dataset sleep-EDF-153 --out_dir datasets/sleep-EDF-153" to download dataset, but it always shows error. 
![image](https://user-images.githubusercontent.com/24765102/70318458-16b0d680-185b-11ea-80f9-b27ea6680b2b.png)

**Comment by xiaoyongzhu** [comment]
> How do I download dataset?
> I use "ut fetch --dataset sleep-EDF-153 --out_dir datasets/sleep-EDF-153" to download dataset, but it always shows error.
> ![image](https://user-images.githubusercontent.com/24765102/70318458-16b0d680-185b-11ea-80f9-b27ea6680b2b.png)

Didn't look into the code, but I'm using Linux and it works fine.
