### ISSUE TITLE
How  to use ut cv_experiment and ut extract_hypno?

### ISSUE THREAD

**Issue by ljyljy** [perslev/U-Time#22]
Thanks for sharing the project.
I have a question: How to use ut cv_experiment and ut extract_hypno for experiments?
It seems that only XML files can be read in extract_hypno. How to use extract_hypno in PSG files (such as sedf_sc)?

Could you describe the usage of ut cv_experiment and ut extract_hypno in more detail?
Thank you very much!

**Comment by ljyljy** [comment]
Thanks for sharing the project.
I have a question: How to use ut cv_experiment and ut extract_hypno for experiments?
It seems that only XML files can be read in extract_hypno. How to use extract_hypno in PSG files (such as sedf_sc)?

Could you describe the usage of ut cv_experiment and ut extract_hypno in more detail? 
Thank you very much!

**Comment by perslev** [comment]
Hi! Some hypnogram formats such as .edf can be loaded directly and does not really require the `extract_hypno.py` script. However, for consistency you can use the script to make all hypnograms the same format across the datasets.

I had an old version of the script in the repo for some reason, which is why you were not able to use it for e.g. EDF files. I have added the correct version. Please pull the latest version and let me know if you still experience issues :)

**Comment by ljyljy** [comment]
thx a lot! ^ ^
