### ISSUE TITLE
[WARNING] Found empty class inds array for study H5SleepStudy

### ISSUE THREAD

**Issue by xiaoshijiu1999** [perslev/U-Time#36]
When I was training the model, I encountered some warnings like **"[WARNING] Found empty class inds array for study H5SleepStudy(open=True, loaded=True, identifier=tr13-0170, N channels: 7, sample_rate=128.0, hypnogram=True) and class 4"**.May I ask why this situation occurs? Which step may be the problem?

**Comment by perslev** [comment]
Hi,

This occurs during sampling of a batch. When a batch element is selected, a random sleep stage is first selected, then a sleep study is selected from some dataset and then a window of signal is selected within that study so that it contains at least 1 segment of the selected sleep stage. Please refer to the paper for details on this sampling mechanism.

However, if the study does not contain the initially selected class at all, then this warning is shown for informative purposes and a new study is selected. It is normal that some studies do not display all sleep stages, so these warnings are usually not an issue.

Cheers,
Mathias
