### ISSUE TITLE
Instructions to use custom time series data

### ISSUE THREAD

**Issue by maksimovkonstantin** [perslev/U-Time#4]
Hi!

Nice work! Could you also point out some instructions on how to properly adjust codebase to use on my custom time series?

**Comment by perslev** [comment]
Hi! Thank you for your interest in our work.

Depending on how much of our codebase you would like to use, I would suggest one of the following strategies:

1) If you already have a data loading and training pipeline of your own, perhaps taking out the U-Time model definition and plugging it in might be the easiest.

2) If you would like to leverage the rest of our code as well, I suggest you try to prepare your data so that it follows the general folder structure as generated by e.g. the 'ut fetch' command. Most importantly, you should split the data storing the signals and the labels into two separate files and store them in one folder for each subject.

Then, have a look at the modules in https://github.com/perslev/U-Time/tree/master/utime/io. You should implement two function for loading and extracting the relevant data and attributes from your custom file-types and register them within the io package (see e.g. https://github.com/perslev/U-Time/blob/master/utime/io/file_loaders/psg_file_loaders.py line 123-131). Hopefully then everything else will work :-)

If you choose to go with 2), feel free to update me on any issues that you experience. It is already on my to-do to generalise this codebase to other time-series settings. Unfortunately, I am on a leave of absence currently and do not have much available time, but I would be happy to look into it as soon as I am back.

**Comment by maksimovkonstantin** [comment]
Thank you a lot for such detailed points! Will try and will post some results in the nearest future.
