### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/home/zch/anaconda3/envs/u-sleep/lib/python3.7/site-packages/utime/bin/defaults'

### ISSUE THREAD

**Issue by CandyZhao123** [perslev/U-Time#40]
Hi, when I init a project, there is a problem.  

FileNotFoundError: [Errno 2] No such file or directory: '/home/zch/anaconda3/envs/u-sleep/lib/python3.7/site-packages/utime/bin/defaults'

How can I solve it ,thank you! 
![image](https://user-images.githubusercontent.com/88925139/130403955-2318a2e5-444a-4726-abe0-59122590d7e8.png)

**Comment by emleeee** [comment]
Did you have the ERROR that utime and mpunet require the different version of packages ?

Just like:"ERROR: mpunet 0.2.12 has requirement matplotlib>=3.3.0, but you'll have matplotlib 3.1.3 which is incompatible.
"   
and "ERROR: utime 0.0.2 has requirement matplotlib==3.1.3, but you'll have matplotlib 3.4.3 which is incompatible.“

**Comment by emleeee** [comment]
Hi！I have the same question. But i have another question begore this:

Did you have the ERROR that utime and mpunet require the different version of packages ?

Just like:"ERROR: mpunet 0.2.12 has requirement matplotlib>=3.3.0, but you'll have matplotlib 3.1.3 which is incompatible.
"
and "ERROR: utime 0.0.2 has requirement matplotlib==3.1.3, but you'll have matplotlib 3.4.3 which is incompatible.“

**Comment by emleeee** [comment]
Hi！I have the same question. But i have another question begore this:

Did you have the ERROR that utime and mpunet require the different version of packages ?

Just like:"ERROR: mpunet 0.2.12 has requirement matplotlib>=3.3.0, but you'll have matplotlib 3.1.3 which is incompatible.
"
and "ERROR: utime 0.0.2 has requirement matplotlib==3.1.3, but you'll have matplotlib 3.4.3 which is incompatible.“

Did you meet this problem?Thank you!

**Comment by emleeee** [comment]
Hi！I have the same question. But i have another question begore this:

Did you have the ERROR that utime and mpunet require the different version of packages ?

Just like:"ERROR: mpunet 0.2.12 has requirement matplotlib>=3.3.0, but you'll have matplotlib 3.1.3 which is incompatible.
"  Then I updated this package.
But "ERROR: utime 0.0.2 has requirement matplotlib==3.1.3, but you'll have matplotlib 3.4.3 which is incompatible.“ 

Did you meet this problem?Thank you!

**Comment by CandyZhao123** [comment]
Hello!&nbsp;
I think your problem is the version of the package.&nbsp;
The original project requires a lower version of the installation package, and you install a higher version.
You can try to reduce the software version to the project requirements.&nbsp;
Good luck!






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "perslev/U-Time"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月11日(星期四) 上午9:19
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [perslev/U-Time] FileNotFoundError: [Errno 2] No such file or directory: '/home/zch/anaconda3/envs/u-sleep/lib/python3.7/site-packages/utime/bin/defaults' (#40)





 
Did you have the ERROR that utime and mpunet require the different version of packages ?
 
Just like:"ERROR: mpunet 0.2.12 has requirement matplotlib&gt;=3.3.0, but you'll have matplotlib 3.1.3 which is incompatible.
 "
 and "ERROR: utime 0.0.2 has requirement matplotlib==3.1.3, but you'll have matplotlib 3.4.3 which is incompatible.“
 
—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by CandyZhao123** [comment]
Hello!&nbsp;
I think your problem is the version of the package.&nbsp;
The original project requires a lower version of the installation package, and you install a higher version.&nbsp;
You can try to reduce the software version to the project requirements.&nbsp;


In fact, I didn't run u-time successfully.&nbsp;
It always has one mistake or another.


Good luck!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "perslev/U-Time"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月11日(星期四) 上午9:21
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [perslev/U-Time] FileNotFoundError: [Errno 2] No such file or directory: '/home/zch/anaconda3/envs/u-sleep/lib/python3.7/site-packages/utime/bin/defaults' (#40)





 
Hi！I have the same question. But i have another question begore this:
 
Did you have the ERROR that utime and mpunet require the different version of packages ?
 
Just like:"ERROR: mpunet 0.2.12 has requirement matplotlib&gt;=3.3.0, but you'll have matplotlib 3.1.3 which is incompatible.
 "
 and "ERROR: utime 0.0.2 has requirement matplotlib==3.1.3, but you'll have matplotlib 3.4.3 which is incompatible.“
 
Did you meet this problem?Thank you!
 
—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by emleeee** [comment]
Hi!it seems that I run usleep successfully. I just ran the first command in the demo again:git clone http://github.com/perslev/U-time.gitI'm new in DL and CS. I may have mistakes. I hope it's helpful to u发自我的华为手机-------- 原始邮件 --------发件人： CandyZhao123 ***@***.***>日期： 2021年11月11日周四 11:00收件人： perslev/U-Time ***@***.***>抄送： emleeee ***@***.***>, Comment ***@***.***>主    题： Re: [perslev/U-Time] FileNotFoundError: [Errno 2] No such file or directory: '/home/zch/anaconda3/envs/u-sleep/lib/python3.7/site-packages/utime/bin/defaults' (#40)

Hello!&nbsp;



I think your problem is the version of the package.&nbsp;



The original project requires a lower version of the installation package, and you install a higher version.



You can try to reduce the software version to the project requirements.&nbsp;



Good luck!



























------------------&nbsp;原始邮件&nbsp;------------------



发件人:                                                                                                                        "perslev/U-Time"                                                                                    ***@***.***&gt;;



发送时间:&nbsp;2021年11月11日(星期四) 上午9:19



***@***.***&gt;;



***@***.***&gt;;"State ***@***.***&gt;;



主题:&nbsp;Re: [perslev/U-Time] FileNotFoundError: [Errno 2] No such file or directory: '/home/zch/anaconda3/envs/u-sleep/lib/python3.7/site-packages/utime/bin/defaults' (#40)























 



Did you have the ERROR that utime and mpunet require the different version of packages ?



 



Just like:"ERROR: mpunet 0.2.12 has requirement matplotlib&gt;=3.3.0, but you'll have matplotlib 3.1.3 which is incompatible.



 "



 and "ERROR: utime 0.0.2 has requirement matplotlib==3.1.3, but you'll have matplotlib 3.4.3 which is incompatible.“



 



—



You are receiving this because you modified the open/close state.



Reply to this email directly, view it on GitHub, or unsubscribe.



Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by emleeee** [comment]
Hi!

it seems that I run usleep successfully. I just ran the first command in the demo again:"git clone http://github.com/perslev/U-time.git" 

I'm new in DL and CS. I may have mistakes. I hope it's helpful to u!
