### ISSUE TITLE
Great work, but too complicated

### ISSUE THREAD

**Issue by ZichenMiao** [perslev/U-Time#41]
I really admire your efforts to make it a real commercial-style package. But it's too complicated to read and modify. I just want to change it to pytorch dataloaders, and it has took me a lot of time...

Great work anyway. I just don't know why spend so much time on this research proj code

**Comment by perslev** [comment]
Hi,

Thanks for your feedback. I agree that the code is now quite complicated, but this is exactly because it is research code. We use this codebase for many types of experiments and research projects, and so many features have been added over time. For your specific application, most of it is likely to be useless and only confusing matters. 
However, you are very welcome to just pick and choose parts of the code that you need (e.g., the models and then use your own data loaders, training pipeline etc.). I am not forcing you to use this framework :-) I just made it all available in case someone found it useful.

**Comment by ZichenMiao** [comment]
Respect!
