### ISSUE TITLE
Best use guide?

### ISSUE THREAD

**Issue by skjerns** [perslev/U-Time#58]
Is there something like a best-use guide for U-Sleep?

For example to answer questions such as: 
- Which sets of channels work best
- Are more channels always better than fewer channels?
- should data be bipolar referenced or average referenced or not references

**Comment by perslev** [comment]
Hi @skjerns! Unfortunately, we do not currently have something like that. I can only say that the pre-trained U-Sleep v1.0 model (the one at https://sleep.ai.ku.dk) usually performs best the more channels it receives. The majority vote is not necessarily much better than the predictions made in the single "best performing" channel. However, using more channels relieves you from figuring out which channel is best for your data (again, usually).

As for referencing, our current understanding is that this has little to no influence on performance. That is, referencing is probably unnecessary or may even be used as a data-augmentation technique (e.g., it may be beneficial to feed in many possible deriviations to augment dataset size and improve robustness). Actually, it turns out U-Sleep v1.0 can work with highly arbitrary channel derivations (see https://arxiv.org/pdf/2209.11173.pdf if you are interested).

**Comment by skjerns** [comment]
Thanks, that's good to know :)

And thanks again for making everything open source and open access, this is truly needed!
